// Generated by scripts/generate-route-schemas.ts. Do not edit manually.
export const generatedRouteSchemas: Readonly<Record<string, Readonly<Record<string, unknown>>>> = {
  "GET /v1/connectivity-policy": {
    "querystring": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "operation": {
          "type": "string"
        }
      },
      "required": [
        "operation"
      ]
    }
  },
  "GET /v1/documents/:documentId/current": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "documentId": {
          "type": "string"
        }
      },
      "required": [
        "documentId"
      ]
    }
  },
  "GET /v1/estimate-assemblies": {
    "querystring": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "type": "string"
        }
      }
    }
  },
  "GET /v1/estimate-authority-policies": {
    "querystring": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "currency": {
          "type": "string"
        }
      }
    }
  },
  "GET /v1/estimate-productivity-factors": {
    "querystring": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "type": "string"
        }
      }
    }
  },
  "GET /v1/estimate-proposals/:proposalId/download": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "proposalId": {
          "type": "string"
        }
      },
      "required": [
        "proposalId"
      ]
    }
  },
  "GET /v1/estimate-revisions/:revisionId/delta": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "revisionId": {
          "type": "string"
        }
      },
      "required": [
        "revisionId"
      ]
    }
  },
  "GET /v1/estimate-revisions/:revisionId/quote-comparison": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "revisionId": {
          "type": "string"
        }
      },
      "required": [
        "revisionId"
      ]
    }
  },
  "GET /v1/estimates": {},
  "GET /v1/estimates/:estimateId": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "estimateId": {
          "type": "string"
        }
      },
      "required": [
        "estimateId"
      ]
    }
  },
  "GET /v1/exports/:exportJobId/download": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "exportJobId": {
          "type": "string"
        }
      },
      "required": [
        "exportJobId"
      ]
    }
  },
  "GET /v1/files/:fileId": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "fileId": {
          "type": "string"
        }
      },
      "required": [
        "fileId"
      ]
    }
  },
  "GET /v1/files/:fileId/download": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "fileId": {
          "type": "string"
        }
      },
      "required": [
        "fileId"
      ]
    }
  },
  "GET /v1/materials/:materialId/movements": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "materialId": {
          "type": "string"
        }
      },
      "required": [
        "materialId"
      ]
    }
  },
  "GET /v1/materials/:materialId/mtr-reviews": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "materialId": {
          "type": "string"
        }
      },
      "required": [
        "materialId"
      ]
    }
  },
  "GET /v1/materials/:materialId/pmi-requirement": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "materialId": {
          "type": "string"
        }
      },
      "required": [
        "materialId"
      ]
    }
  },
  "GET /v1/portal/assigned-work": {},
  "GET /v1/project-controls-authority-policies": {},
  "GET /v1/projects": {},
  "GET /v1/projects/:projectId/audit": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "GET /v1/projects/:projectId/configurations/:configurationCode/current": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        },
        "configurationCode": {
          "type": "string"
        }
      },
      "required": [
        "configurationCode",
        "projectId"
      ]
    }
  },
  "GET /v1/projects/:projectId/controls": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "GET /v1/projects/:projectId/cost-summary": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "GET /v1/projects/:projectId/notifications": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "GET /v1/projects/:projectId/readiness": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "GET /v1/projects/:projectId/report-dashboard": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "GET /v1/projects/:projectId/reports": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "GET /v1/projects/:projectId/search": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    },
    "querystring": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "q": {
          "type": "string"
        }
      },
      "required": [
        "q"
      ]
    }
  },
  "GET /v1/projects/:projectId/turnover/:packageId/compare": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        },
        "packageId": {
          "type": "string"
        }
      },
      "required": [
        "packageId",
        "projectId"
      ]
    },
    "querystring": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "from": {
          "type": "string"
        },
        "to": {
          "type": "string"
        }
      },
      "required": [
        "from",
        "to"
      ]
    }
  },
  "GET /v1/reports/:reportId": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "reportId": {
          "type": "string"
        }
      },
      "required": [
        "reportId"
      ]
    }
  },
  "GET /v1/reports/:reportId/download": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "reportId": {
          "type": "string"
        }
      },
      "required": [
        "reportId"
      ]
    },
    "querystring": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "format": {
          "type": "string",
          "enum": [
            "html",
            "json"
          ]
        }
      },
      "required": [
        "format"
      ]
    }
  },
  "GET /v1/schedules/:scheduleId/look-ahead": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "scheduleId": {
          "type": "string"
        }
      },
      "required": [
        "scheduleId"
      ]
    },
    "querystring": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "windowDays": {
          "type": "number"
        }
      },
      "required": [
        "windowDays"
      ]
    }
  },
  "GET /v1/session": {},
  "GET /v1/subcontractor-assignments/:assignmentId/mobilization-readiness": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "assignmentId": {
          "type": "string"
        }
      },
      "required": [
        "assignmentId"
      ]
    }
  },
  "GET /v1/turnover-packages/:packageId/readiness": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "packageId": {
          "type": "string"
        }
      },
      "required": [
        "packageId"
      ]
    }
  },
  "POST /v1/access/assignments": {
    "body": {}
  },
  "POST /v1/access/assignments/:assignmentId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "assignmentId": {
          "type": "string"
        }
      },
      "required": [
        "assignmentId"
      ]
    }
  },
  "POST /v1/access/assignments/:assignmentId/revoke": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "assignmentId": {
          "type": "string"
        }
      },
      "required": [
        "assignmentId"
      ]
    }
  },
  "POST /v1/access/delegations": {
    "body": {}
  },
  "POST /v1/access/delegations/:delegationId/approve": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "delegationId": {
          "type": "string"
        }
      },
      "required": [
        "delegationId"
      ]
    }
  },
  "POST /v1/access/delegations/:delegationId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "delegationId": {
          "type": "string"
        }
      },
      "required": [
        "delegationId"
      ]
    }
  },
  "POST /v1/access/delegations/:delegationId/revoke": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "delegationId": {
          "type": "string"
        }
      },
      "required": [
        "delegationId"
      ]
    }
  },
  "POST /v1/completion-boundaries/:boundaryId/turnover-packages": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "type": "string"
        },
        "recipientScope": {
          "type": "string"
        },
        "materialItemIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "code",
        "materialItemIds",
        "recipientScope"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "boundaryId": {
          "type": "string"
        }
      },
      "required": [
        "boundaryId"
      ]
    }
  },
  "POST /v1/completion-boundaries/:boundaryId/turnover-requirements": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "type": "string"
        },
        "recordClass": {
          "type": "string",
          "enum": [
            "material",
            "pmi",
            "ncr",
            "punch",
            "document_revision"
          ]
        },
        "required": {
          "type": "boolean"
        },
        "notApplicableAllowed": {
          "type": "boolean"
        },
        "acceptanceAuthority": {
          "type": "string"
        }
      },
      "required": [
        "acceptanceAuthority",
        "code",
        "notApplicableAllowed",
        "recordClass",
        "required"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "boundaryId": {
          "type": "string"
        }
      },
      "required": [
        "boundaryId"
      ]
    }
  },
  "POST /v1/document-distributions/:distributionId/acknowledge": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "meaning": {
          "type": "string"
        }
      },
      "required": [
        "expectedVersion",
        "meaning"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "distributionId": {
          "type": "string"
        }
      },
      "required": [
        "distributionId"
      ]
    }
  },
  "POST /v1/document-distributions/:distributionId/download": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "distributionId": {
          "type": "string"
        }
      },
      "required": [
        "distributionId"
      ]
    }
  },
  "POST /v1/documents/:documentId/revisions": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "revision": {
          "type": "string"
        },
        "purpose": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "fileId": {
          "type": "string"
        },
        "requiredApprovalCount": {
          "type": "number"
        }
      },
      "required": [
        "fileId",
        "purpose",
        "requiredApprovalCount",
        "revision",
        "source"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "documentId": {
          "type": "string"
        }
      },
      "required": [
        "documentId"
      ]
    }
  },
  "POST /v1/estimate-assemblies": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "businessScopeOrganizationId": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "revision": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "costCode": {
          "type": "string"
        },
        "unitCode": {
          "type": "string"
        },
        "baseLaborHoursPerUnit": {
          "type": "string"
        },
        "laborRatePerHour": {
          "type": "string"
        },
        "materialUnitCost": {
          "type": "string"
        },
        "equipmentUnitCost": {
          "type": "string"
        },
        "subcontractUnitCost": {
          "type": "string"
        },
        "supersedesRevisionId": {
          "type": "string",
          "nullable": true
        }
      },
      "required": [
        "baseLaborHoursPerUnit",
        "businessScopeOrganizationId",
        "code",
        "costCode",
        "description",
        "equipmentUnitCost",
        "laborRatePerHour",
        "materialUnitCost",
        "revision",
        "subcontractUnitCost",
        "supersedesRevisionId",
        "unitCode"
      ]
    }
  },
  "POST /v1/estimate-assemblies/:assemblyId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "approve"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "assemblyId": {
          "type": "string"
        }
      },
      "required": [
        "assemblyId"
      ]
    }
  },
  "POST /v1/estimate-authority-policies": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "businessScopeOrganizationId": {
          "type": "string"
        },
        "currency": {
          "type": "string"
        },
        "revision": {
          "type": "string"
        },
        "standardEstimateApprovalLimit": {
          "type": "string"
        },
        "standardQuoteSelectionLimit": {
          "type": "string"
        },
        "standardProposalApprovalLimit": {
          "type": "string"
        },
        "estimateAboveThresholdQualification": {
          "type": "string"
        },
        "quoteAboveThresholdQualification": {
          "type": "string"
        },
        "proposalAboveThresholdQualification": {
          "type": "string"
        },
        "supersedesRevisionId": {
          "type": "string",
          "nullable": true
        }
      },
      "required": [
        "businessScopeOrganizationId",
        "currency",
        "estimateAboveThresholdQualification",
        "proposalAboveThresholdQualification",
        "quoteAboveThresholdQualification",
        "revision",
        "standardEstimateApprovalLimit",
        "standardProposalApprovalLimit",
        "standardQuoteSelectionLimit",
        "supersedesRevisionId"
      ]
    }
  },
  "POST /v1/estimate-authority-policies/:policyId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "approve"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "policyId": {
          "type": "string"
        }
      },
      "required": [
        "policyId"
      ]
    }
  },
  "POST /v1/estimate-lines/:lineId/remove": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "lineId": {
          "type": "string"
        }
      },
      "required": [
        "lineId"
      ]
    }
  },
  "POST /v1/estimate-productivity-factors": {
    "body": {}
  },
  "POST /v1/estimate-productivity-factors/:factorId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "approve"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "factorId": {
          "type": "string"
        }
      },
      "required": [
        "factorId"
      ]
    }
  },
  "POST /v1/estimate-proposals/:proposalId/handoff": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        },
        "authorizationReference": {
          "type": "string"
        },
        "adjustmentCostCodes": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "contingency": {
              "type": "string"
            },
            "escalation": {
              "type": "string"
            },
            "markup": {
              "type": "string"
            },
            "tax": {
              "type": "string"
            }
          },
          "required": [
            "contingency",
            "escalation",
            "markup",
            "tax"
          ]
        }
      },
      "required": [
        "adjustmentCostCodes",
        "authorizationReference",
        "projectId"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "proposalId": {
          "type": "string"
        }
      },
      "required": [
        "proposalId"
      ]
    }
  },
  "POST /v1/estimate-proposals/:proposalId/issue": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "proposalId": {
          "type": "string"
        }
      },
      "required": [
        "proposalId"
      ]
    }
  },
  "POST /v1/estimate-proposals/:proposalId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "approve"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "proposalId": {
          "type": "string"
        }
      },
      "required": [
        "proposalId"
      ]
    }
  },
  "POST /v1/estimate-quotes/:quoteId/select": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "quoteId": {
          "type": "string"
        }
      },
      "required": [
        "quoteId"
      ]
    }
  },
  "POST /v1/estimate-revisions/:revisionId/lines": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "lineKey": {
          "type": "string",
          "nullable": true
        },
        "parentLineKey": {
          "type": "string",
          "nullable": true
        },
        "sortOrder": {
          "type": "number"
        },
        "costCode": {
          "type": "string",
          "nullable": true
        },
        "bidItemCode": {
          "type": "string",
          "nullable": true
        },
        "alternateCode": {
          "type": "string",
          "nullable": true
        },
        "wbsCode": {
          "type": "string",
          "nullable": true
        },
        "workPackageCode": {
          "type": "string",
          "nullable": true
        },
        "assemblyRevisionId": {
          "type": "string",
          "nullable": true
        },
        "description": {
          "type": "string"
        },
        "quantity": {
          "type": "string"
        },
        "unitCode": {
          "type": "string",
          "nullable": true
        },
        "baseLaborHoursPerUnit": {
          "type": "string",
          "nullable": true
        },
        "laborRatePerHour": {
          "type": "string",
          "nullable": true
        },
        "materialUnitCost": {
          "type": "string",
          "nullable": true
        },
        "equipmentUnitCost": {
          "type": "string",
          "nullable": true
        },
        "subcontractUnitCost": {
          "type": "string",
          "nullable": true
        },
        "allowanceCost": {
          "type": "string"
        },
        "otherCost": {
          "type": "string"
        },
        "productivityFactorRevisionIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "allowanceCost",
        "alternateCode",
        "assemblyRevisionId",
        "baseLaborHoursPerUnit",
        "bidItemCode",
        "costCode",
        "description",
        "equipmentUnitCost",
        "laborRatePerHour",
        "lineKey",
        "materialUnitCost",
        "otherCost",
        "parentLineKey",
        "productivityFactorRevisionIds",
        "quantity",
        "sortOrder",
        "subcontractUnitCost",
        "unitCode",
        "wbsCode",
        "workPackageCode"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "revisionId": {
          "type": "string"
        }
      },
      "required": [
        "revisionId"
      ]
    }
  },
  "POST /v1/estimate-revisions/:revisionId/proposals": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "revisionId": {
          "type": "string"
        }
      },
      "required": [
        "revisionId"
      ]
    }
  },
  "POST /v1/estimate-revisions/:revisionId/quotes": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "revisionId": {
          "type": "string"
        }
      },
      "required": [
        "revisionId"
      ]
    }
  },
  "POST /v1/estimate-revisions/:revisionId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "approve"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "revisionId": {
          "type": "string"
        }
      },
      "required": [
        "revisionId"
      ]
    }
  },
  "POST /v1/estimate-revisions/:revisionId/submit": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "revisionId": {
          "type": "string"
        }
      },
      "required": [
        "revisionId"
      ]
    }
  },
  "POST /v1/estimates": {
    "body": {}
  },
  "POST /v1/estimates/:estimateId/revisions": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "estimateId": {
          "type": "string"
        }
      },
      "required": [
        "estimateId"
      ]
    }
  },
  "POST /v1/exports/:exportJobId/process": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "exportJobId": {
          "type": "string"
        }
      },
      "required": [
        "exportJobId"
      ]
    }
  },
  "POST /v1/files/:fileId/release": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "fileId": {
          "type": "string"
        }
      },
      "required": [
        "fileId"
      ]
    }
  },
  "POST /v1/files/:fileId/validation": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "fileId": {
          "type": "string"
        }
      },
      "required": [
        "fileId"
      ]
    }
  },
  "POST /v1/identity/accounts": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "businessScopeOrganizationId": {
          "type": "string"
        },
        "personId": {
          "type": "string"
        },
        "displayName": {
          "type": "string"
        },
        "qualificationCodes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "businessScopeOrganizationId",
        "displayName",
        "personId",
        "qualificationCodes"
      ]
    }
  },
  "POST /v1/identity/accounts/:accountId/activate": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "businessScopeOrganizationId": {
          "type": "string"
        },
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "businessScopeOrganizationId",
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "accountId": {
          "type": "string"
        }
      },
      "required": [
        "accountId"
      ]
    }
  },
  "POST /v1/identity/accounts/:accountId/disable": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "businessScopeOrganizationId": {
          "type": "string"
        },
        "expectedVersion": {
          "type": "number"
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "businessScopeOrganizationId",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "accountId": {
          "type": "string"
        }
      },
      "required": [
        "accountId"
      ]
    }
  },
  "POST /v1/identity/accounts/:accountId/external-identities": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "businessScopeOrganizationId": {
          "type": "string"
        },
        "issuer": {
          "type": "string"
        },
        "subject": {
          "type": "string"
        },
        "identityType": {
          "type": "string",
          "enum": [
            "internal",
            "guest",
            "service",
            "break_glass"
          ]
        }
      },
      "required": [
        "businessScopeOrganizationId",
        "identityType",
        "issuer",
        "subject"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "accountId": {
          "type": "string"
        }
      },
      "required": [
        "accountId"
      ]
    }
  },
  "POST /v1/imports/:importJobId/commit": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "importJobId": {
          "type": "string"
        }
      },
      "required": [
        "importJobId"
      ]
    }
  },
  "POST /v1/imports/:importJobId/validate": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "importJobId": {
          "type": "string"
        }
      },
      "required": [
        "importJobId"
      ]
    }
  },
  "POST /v1/inspection-plans/:planRevisionId/approve": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "planRevisionId": {
          "type": "string"
        }
      },
      "required": [
        "planRevisionId"
      ]
    }
  },
  "POST /v1/inspections/:inspectionId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "accept"
          ]
        },
        "meaningOrReason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "meaningOrReason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "inspectionId": {
          "type": "string"
        }
      },
      "required": [
        "inspectionId"
      ]
    }
  },
  "POST /v1/integrations/:messageId/process": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "outcome": {
          "type": "string",
          "enum": [
            "success",
            "failure"
          ]
        },
        "errorReason": {
          "type": "string",
          "nullable": true
        }
      },
      "required": [
        "errorReason",
        "expectedVersion",
        "outcome"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "messageId": {
          "type": "string"
        }
      },
      "required": [
        "messageId"
      ]
    }
  },
  "POST /v1/integrations/:messageId/reconcile": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "resolution": {
          "type": "string",
          "enum": [
            "accept",
            "replay"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "expectedVersion",
        "reason",
        "resolution"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "messageId": {
          "type": "string"
        }
      },
      "required": [
        "messageId"
      ]
    }
  },
  "POST /v1/legal-holds/:holdId/release": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "holdId": {
          "type": "string"
        }
      },
      "required": [
        "holdId"
      ]
    }
  },
  "POST /v1/materials/:materialId/issue": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "materialId": {
          "type": "string"
        }
      },
      "required": [
        "materialId"
      ]
    }
  },
  "POST /v1/materials/:materialId/move": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "materialId": {
          "type": "string"
        }
      },
      "required": [
        "materialId"
      ]
    }
  },
  "POST /v1/materials/:materialId/mtr-reviews": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "materialId": {
          "type": "string"
        }
      },
      "required": [
        "materialId"
      ]
    }
  },
  "POST /v1/materials/:materialId/pmi": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "materialId": {
          "type": "string"
        }
      },
      "required": [
        "materialId"
      ]
    }
  },
  "POST /v1/materials/:materialId/pmi-overrides": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "required": {
          "type": "boolean"
        },
        "justification": {
          "type": "string"
        },
        "governingDocumentRevisionId": {
          "type": "string"
        }
      },
      "required": [
        "governingDocumentRevisionId",
        "justification",
        "required"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "materialId": {
          "type": "string"
        }
      },
      "required": [
        "materialId"
      ]
    }
  },
  "POST /v1/materials/:materialId/receiving-inspection/accept": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "materialId": {
          "type": "string"
        }
      },
      "required": [
        "materialId"
      ]
    }
  },
  "POST /v1/materials/:materialId/release": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "materialId": {
          "type": "string"
        }
      },
      "required": [
        "materialId"
      ]
    }
  },
  "POST /v1/materials/:materialId/return": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "materialId": {
          "type": "string"
        }
      },
      "required": [
        "materialId"
      ]
    }
  },
  "POST /v1/materials/:materialId/split": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "materialId": {
          "type": "string"
        }
      },
      "required": [
        "materialId"
      ]
    }
  },
  "POST /v1/mobilization-requirements/:requirementId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "accept"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "requirementId": {
          "type": "string"
        }
      },
      "required": [
        "requirementId"
      ]
    }
  },
  "POST /v1/mobilization-requirements/:requirementId/submission": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "requirementId": {
          "type": "string"
        }
      },
      "required": [
        "requirementId"
      ]
    }
  },
  "POST /v1/ncrs/:ncrId/close": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ncrId": {
          "type": "string"
        }
      },
      "required": [
        "ncrId"
      ]
    }
  },
  "POST /v1/ncrs/:ncrId/disposition": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ncrId": {
          "type": "string"
        }
      },
      "required": [
        "ncrId"
      ]
    }
  },
  "POST /v1/ncrs/:ncrId/disposition/approve": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ncrId": {
          "type": "string"
        }
      },
      "required": [
        "ncrId"
      ]
    }
  },
  "POST /v1/ncrs/:ncrId/reinspection": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "evidenceFileId": {
          "type": "string"
        }
      },
      "required": [
        "evidenceFileId",
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ncrId": {
          "type": "string"
        }
      },
      "required": [
        "ncrId"
      ]
    }
  },
  "POST /v1/notifications/:notificationId/process": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "outcome": {
          "type": "string",
          "enum": [
            "success",
            "failure"
          ]
        },
        "errorReason": {
          "type": "string",
          "nullable": true
        }
      },
      "required": [
        "errorReason",
        "expectedVersion",
        "outcome"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "notificationId": {
          "type": "string"
        }
      },
      "required": [
        "notificationId"
      ]
    }
  },
  "POST /v1/offline-drafts/:draftId/synchronize": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "outcome": {
          "type": "string",
          "enum": [
            "conflict",
            "reject",
            "accept"
          ]
        },
        "conflictReason": {
          "type": "string",
          "nullable": true
        }
      },
      "required": [
        "conflictReason",
        "expectedVersion",
        "outcome"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "draftId": {
          "type": "string"
        }
      },
      "required": [
        "draftId"
      ]
    }
  },
  "POST /v1/organizations/:organizationId/file-uploads": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  "POST /v1/pmi-overrides/:overrideId/approve": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "expectedMaterialVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedMaterialVersion",
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "overrideId": {
          "type": "string"
        }
      },
      "required": [
        "overrideId"
      ]
    }
  },
  "POST /v1/pmi/:pmiId/accept": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "pmiId": {
          "type": "string"
        }
      },
      "required": [
        "pmiId"
      ]
    }
  },
  "POST /v1/portal/projects/:projectId/work-packages/:workPackageId/submissions": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "category": {
          "type": "string",
          "enum": [
            "inspection",
            "progress",
            "deficiency",
            "turnover"
          ]
        },
        "title": {
          "type": "string"
        },
        "claimedProgressPercent": {
          "type": "number",
          "nullable": true
        },
        "evidenceFileIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "category",
        "claimedProgressPercent",
        "evidenceFileIds",
        "title"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        },
        "workPackageId": {
          "type": "string"
        }
      },
      "required": [
        "projectId",
        "workPackageId"
      ]
    }
  },
  "POST /v1/procurement-bid-packages/:bidPackageId/award": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "reason": {
          "type": "string"
        },
        "purchaseOrderReference": {
          "type": "string"
        },
        "revision": {
          "type": "string"
        }
      },
      "required": [
        "expectedVersion",
        "purchaseOrderReference",
        "reason",
        "revision"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "bidPackageId": {
          "type": "string"
        }
      },
      "required": [
        "bidPackageId"
      ]
    }
  },
  "POST /v1/procurement-bid-packages/:bidPackageId/offers": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "bidPackageId": {
          "type": "string"
        }
      },
      "required": [
        "bidPackageId"
      ]
    }
  },
  "POST /v1/procurement-bid-packages/:bidPackageId/recommend": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "offerKey": {
          "type": "string"
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "expectedVersion",
        "offerKey",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "bidPackageId": {
          "type": "string"
        }
      },
      "required": [
        "bidPackageId"
      ]
    }
  },
  "POST /v1/procurement-commitments/:commitmentId/status-events": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "commitmentId": {
          "type": "string"
        }
      },
      "required": [
        "commitmentId"
      ]
    }
  },
  "POST /v1/procurement-requisitions/:requisitionId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "approve"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "requisitionId": {
          "type": "string"
        }
      },
      "required": [
        "requisitionId"
      ]
    }
  },
  "POST /v1/procurement-requisitions/:requisitionId/submit": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "requisitionId": {
          "type": "string"
        }
      },
      "required": [
        "requisitionId"
      ]
    }
  },
  "POST /v1/project-changes/:changeId/baseline": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "changeId": {
          "type": "string"
        }
      },
      "required": [
        "changeId"
      ]
    }
  },
  "POST /v1/project-changes/:changeId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "approve"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "changeId": {
          "type": "string"
        }
      },
      "required": [
        "changeId"
      ]
    }
  },
  "POST /v1/project-configurations/:configurationId/approve": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "configurationId": {
          "type": "string"
        }
      },
      "required": [
        "configurationId"
      ]
    }
  },
  "POST /v1/project-control-baselines/:baselineId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "approve"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "baselineId": {
          "type": "string"
        }
      },
      "required": [
        "baselineId"
      ]
    }
  },
  "POST /v1/project-control-baselines/:baselineId/submit": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "baselineId": {
          "type": "string"
        }
      },
      "required": [
        "baselineId"
      ]
    }
  },
  "POST /v1/project-controls-authority-policies": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "businessScopeOrganizationId": {
          "type": "string"
        },
        "currency": {
          "type": "string"
        },
        "revision": {
          "type": "string"
        },
        "standardChangeApprovalLimit": {
          "type": "string"
        },
        "standardProcurementAwardLimit": {
          "type": "string"
        },
        "changeAboveThresholdQualification": {
          "type": "string"
        },
        "procurementAboveThresholdQualification": {
          "type": "string"
        },
        "supersedesRevisionId": {
          "type": "string",
          "nullable": true
        }
      },
      "required": [
        "businessScopeOrganizationId",
        "changeAboveThresholdQualification",
        "currency",
        "procurementAboveThresholdQualification",
        "revision",
        "standardChangeApprovalLimit",
        "standardProcurementAwardLimit",
        "supersedesRevisionId"
      ]
    }
  },
  "POST /v1/project-controls-authority-policies/:policyId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "approve"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "policyId": {
          "type": "string"
        }
      },
      "required": [
        "policyId"
      ]
    }
  },
  "POST /v1/project-cost-entries/:entryId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "accept"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "entryId": {
          "type": "string"
        }
      },
      "required": [
        "entryId"
      ]
    }
  },
  "POST /v1/project-progress-claims/:claimId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "accept"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "claimId": {
          "type": "string"
        }
      },
      "required": [
        "claimId"
      ]
    }
  },
  "POST /v1/projects": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "businessScopeOrganizationId": {
          "type": "string"
        },
        "number": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "customerOrganizationId": {
          "type": "string"
        },
        "facilityId": {
          "type": "string"
        },
        "timeZone": {
          "type": "string"
        },
        "readiness": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "scopeStatement": {
              "type": "string"
            },
            "governingRequirementReferences": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "plannedStartDate": {
              "type": "string"
            },
            "plannedFinishDate": {
              "type": "string"
            },
            "responsibleRoleCodes": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "governingRequirementReferences",
            "plannedFinishDate",
            "plannedStartDate",
            "responsibleRoleCodes",
            "scopeStatement"
          ]
        }
      },
      "required": [
        "businessScopeOrganizationId",
        "customerOrganizationId",
        "facilityId",
        "name",
        "number",
        "readiness",
        "timeZone"
      ]
    }
  },
  "POST /v1/projects/:projectId/activate": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/changes": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "baselineId": {
          "type": "string"
        },
        "number": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "origin": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "scheduleDaysImpact": {
          "type": "string"
        },
        "quotationReference": {
          "type": "string",
          "nullable": true
        },
        "evidenceFileIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "lineImpacts": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "baselineLineKey": {
                "type": "string"
              },
              "quantityDelta": {
                "type": "string"
              },
              "amountDelta": {
                "type": "string"
              },
              "reason": {
                "type": "string"
              }
            },
            "required": [
              "amountDelta",
              "baselineLineKey",
              "quantityDelta",
              "reason"
            ]
          }
        }
      },
      "required": [
        "baselineId",
        "description",
        "evidenceFileIds",
        "lineImpacts",
        "number",
        "origin",
        "quotationReference",
        "scheduleDaysImpact",
        "title"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/completion-boundaries": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "boundaryType": {
          "type": "string",
          "enum": [
            "system",
            "area",
            "asset",
            "test_package",
            "work_package",
            "contract"
          ]
        },
        "code": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "boundaryType",
        "code",
        "name"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/configurations": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/control-baselines": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/cost-entries": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/documents": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "number": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "discipline": {
          "type": "string"
        }
      },
      "required": [
        "discipline",
        "number",
        "title",
        "type"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/exports": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "recordClass": {
          "type": "string",
          "enum": [
            "material",
            "ncr",
            "punch",
            "document",
            "imported"
          ]
        },
        "recordIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "format": {
          "type": "string",
          "enum": [
            "csv",
            "jsonl"
          ]
        },
        "recipientOrganizationId": {
          "type": "string"
        }
      },
      "required": [
        "format",
        "recipientOrganizationId",
        "recordClass",
        "recordIds"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/file-uploads": {
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/governing-document-links": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "targetType": {
          "type": "string"
        },
        "targetId": {
          "type": "string"
        },
        "documentRevisionId": {
          "type": "string"
        },
        "governingPurpose": {
          "type": "string"
        }
      },
      "required": [
        "documentRevisionId",
        "governingPurpose",
        "targetId",
        "targetType"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/imports": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "schemaName": {
          "type": "string",
          "enum": [
            "punch",
            "material_receipt"
          ]
        },
        "schemaVersion": {
          "type": "number"
        },
        "sourceSystem": {
          "type": "string"
        },
        "rows": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "externalId": {
                "type": "string"
              },
              "payload": {
                "type": "object",
                "additionalProperties": {
                  "type": "string"
                }
              }
            },
            "required": [
              "externalId",
              "payload"
            ]
          }
        }
      },
      "required": [
        "rows",
        "schemaName",
        "schemaVersion",
        "sourceSystem"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/inspection-equipment": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/inspection-plans/revisions": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "templateCode": {
          "type": "string"
        },
        "revision": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "requiredFields": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "applicableTargetTypes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "requiredPerformerQualifications": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "requiredAcceptorQualifications": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "acceptanceReference": {
          "type": "string"
        },
        "minimumAcceptanceAssurance": {
          "type": "string",
          "enum": [
            "mfa",
            "step-up"
          ]
        }
      },
      "required": [
        "acceptanceReference",
        "applicableTargetTypes",
        "minimumAcceptanceAssurance",
        "requiredAcceptorQualifications",
        "requiredFields",
        "requiredPerformerQualifications",
        "revision",
        "templateCode",
        "title"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/inspections": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/integrations/inbox": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "interfaceCode": {
          "type": "string"
        },
        "idempotencyKey": {
          "type": "string"
        },
        "externalId": {
          "type": "string"
        },
        "schemaVersion": {
          "type": "number"
        },
        "payload": {
          "type": "object",
          "additionalProperties": {}
        }
      },
      "required": [
        "externalId",
        "idempotencyKey",
        "interfaceCode",
        "payload",
        "schemaVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/legal-holds": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "targetType": {
          "type": "string"
        },
        "targetId": {
          "type": "string"
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "reason",
        "targetId",
        "targetType"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/materials": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectConfigurationRevisionId": {
          "type": "string"
        },
        "identifier": {
          "type": "string"
        },
        "receiptNumber": {
          "type": "string"
        },
        "purchaseReference": {
          "type": "string"
        },
        "vendorOrganizationId": {
          "type": "string"
        },
        "specification": {
          "type": "string"
        },
        "grade": {
          "type": "string"
        },
        "form": {
          "type": "string"
        },
        "dimensions": {
          "type": "string"
        },
        "quantity": {
          "type": "string"
        },
        "unitCode": {
          "type": "string"
        },
        "heatLot": {
          "type": "string"
        },
        "mtrDocumentRevisionId": {
          "type": "string",
          "nullable": true
        },
        "receiptEvidenceFileIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "storageLocation": {
          "type": "string"
        },
        "mtrRequired": {
          "type": "boolean"
        },
        "receivingInspectionRequired": {
          "type": "boolean"
        },
        "pmiRequired": {
          "type": "boolean"
        },
        "governingPmiRule": {
          "type": "string",
          "nullable": true
        }
      },
      "required": [
        "dimensions",
        "form",
        "governingPmiRule",
        "grade",
        "heatLot",
        "identifier",
        "mtrDocumentRevisionId",
        "mtrRequired",
        "pmiRequired",
        "projectConfigurationRevisionId",
        "purchaseReference",
        "quantity",
        "receiptEvidenceFileIds",
        "receiptNumber",
        "receivingInspectionRequired",
        "specification",
        "storageLocation",
        "unitCode",
        "vendorOrganizationId"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/ncrs": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "number": {
          "type": "string"
        },
        "affectedObjectType": {
          "type": "string",
          "enum": [
            "material",
            "inspection",
            "work"
          ]
        },
        "affectedObjectId": {
          "type": "string"
        },
        "requirementReference": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "containment": {
          "type": "string"
        },
        "evidenceFileIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "responsibleUserId": {
          "type": "string"
        },
        "turnoverRequired": {
          "type": "boolean"
        }
      },
      "required": [
        "affectedObjectId",
        "affectedObjectType",
        "containment",
        "description",
        "evidenceFileIds",
        "number",
        "requirementReference",
        "responsibleUserId",
        "turnoverRequired"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/notifications/dispatch": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "eventType": {
          "type": "string"
        },
        "recordClass": {
          "type": "string",
          "enum": [
            "material",
            "ncr",
            "punch",
            "document",
            "imported"
          ]
        },
        "recordId": {
          "type": "string"
        },
        "recipientUserIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "templateCode": {
          "type": "string"
        },
        "idempotencyKey": {
          "type": "string"
        }
      },
      "required": [
        "eventType",
        "idempotencyKey",
        "recipientUserIds",
        "recordClass",
        "recordId",
        "templateCode"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/offline-drafts": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/organizations": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "participationRole": {
          "type": "string",
          "enum": [
            "business_scope",
            "customer",
            "supplier",
            "subcontractor",
            "inspector",
            "other"
          ]
        }
      },
      "required": [
        "organizationId",
        "participationRole"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/procurement-bid-packages": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "requisitionId": {
          "type": "string"
        },
        "number": {
          "type": "string"
        },
        "bidderOrganizationIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "bidderOrganizationIds",
        "number",
        "requisitionId"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/procurement-requisitions": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/progress-claims": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/punch-items": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/reports": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "formCode": {
          "type": "string",
          "enum": [
            "FORM-PRJ-001",
            "FORM-DOC-001",
            "FORM-MAT-001",
            "FORM-MTR-001",
            "FORM-PMI-001",
            "FORM-INS-001",
            "FORM-NCR-001",
            "FORM-PCH-001",
            "FORM-SUB-001",
            "FORM-SUB-002",
            "FORM-TOV-001"
          ]
        },
        "targetId": {
          "type": "string"
        }
      },
      "required": [
        "formCode",
        "targetId"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/responsibilities": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/retention-dispositions": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "recordClass": {
          "type": "string"
        },
        "targetId": {
          "type": "string"
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "reason",
        "recordClass",
        "targetId"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/retention-policies": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "recordClass": {
          "type": "string"
        },
        "contractReference": {
          "type": "string"
        },
        "retentionDurationDays": {
          "type": "number"
        },
        "dispositionAction": {
          "type": "string",
          "enum": [
            "archive",
            "destroy",
            "anonymize"
          ]
        }
      },
      "required": [
        "contractReference",
        "dispositionAction",
        "recordClass",
        "retentionDurationDays"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/schedules": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "number": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "timeZone": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "number",
        "timeZone"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/structure": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "system",
            "area",
            "work_package",
            "wbs"
          ]
        },
        "parentId": {
          "type": "string",
          "nullable": true
        },
        "code": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "code",
        "name",
        "parentId",
        "type"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  },
  "POST /v1/projects/:projectId/subcontractors/:profileId/assignments": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "approvedScopeCode": {
          "type": "string"
        },
        "workPackageIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "authorizationReference": {
          "type": "string"
        }
      },
      "required": [
        "approvedScopeCode",
        "authorizationReference",
        "workPackageIds"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        },
        "profileId": {
          "type": "string"
        }
      },
      "required": [
        "profileId",
        "projectId"
      ]
    }
  },
  "POST /v1/punch-items/:punchId/close": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "closureMeaning": {
          "type": "string"
        }
      },
      "required": [
        "closureMeaning",
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "punchId": {
          "type": "string"
        }
      },
      "required": [
        "punchId"
      ]
    }
  },
  "POST /v1/punch-items/:punchId/owner-update": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "evidenceFileIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "readyForVerification": {
          "type": "boolean"
        }
      },
      "required": [
        "evidenceFileIds",
        "expectedVersion",
        "readyForVerification"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "punchId": {
          "type": "string"
        }
      },
      "required": [
        "punchId"
      ]
    }
  },
  "POST /v1/punch-items/:punchId/verify": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "verificationEvidenceFileId": {
          "type": "string"
        }
      },
      "required": [
        "expectedVersion",
        "verificationEvidenceFileId"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "punchId": {
          "type": "string"
        }
      },
      "required": [
        "punchId"
      ]
    }
  },
  "POST /v1/retention-dispositions/:dispositionId/approve": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "dispositionId": {
          "type": "string"
        }
      },
      "required": [
        "dispositionId"
      ]
    }
  },
  "POST /v1/retention-dispositions/:dispositionId/execute": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "dispositionId": {
          "type": "string"
        }
      },
      "required": [
        "dispositionId"
      ]
    }
  },
  "POST /v1/retention-policies/:policyId/approve": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "policyId": {
          "type": "string"
        }
      },
      "required": [
        "policyId"
      ]
    }
  },
  "POST /v1/revisions/:revisionId/approve": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "independentApprovalRequired": {
          "type": "boolean"
        }
      },
      "required": [
        "expectedVersion",
        "independentApprovalRequired"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "revisionId": {
          "type": "string"
        }
      },
      "required": [
        "revisionId"
      ]
    }
  },
  "POST /v1/revisions/:revisionId/distributions": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "recipientOrganizationId": {
          "type": "string"
        },
        "recipientUserId": {
          "type": "string",
          "nullable": true
        },
        "workPackageId": {
          "type": "string",
          "nullable": true
        },
        "purpose": {
          "type": "string"
        },
        "acknowledgementRequired": {
          "type": "boolean"
        }
      },
      "required": [
        "acknowledgementRequired",
        "purpose",
        "recipientOrganizationId",
        "recipientUserId",
        "workPackageId"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "revisionId": {
          "type": "string"
        }
      },
      "required": [
        "revisionId"
      ]
    }
  },
  "POST /v1/revisions/:revisionId/release": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedRevisionVersion": {
          "type": "number"
        },
        "expectedDocumentVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedDocumentVersion",
        "expectedRevisionVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "revisionId": {
          "type": "string"
        }
      },
      "required": [
        "revisionId"
      ]
    }
  },
  "POST /v1/schedule-imports/:importId/commit": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "importId": {
          "type": "string"
        }
      },
      "required": [
        "importId"
      ]
    }
  },
  "POST /v1/schedule-revisions/:revisionId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "approve"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "reason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "revisionId": {
          "type": "string"
        }
      },
      "required": [
        "revisionId"
      ]
    }
  },
  "POST /v1/schedule-revisions/:revisionId/submit": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "revisionId": {
          "type": "string"
        }
      },
      "required": [
        "revisionId"
      ]
    }
  },
  "POST /v1/schedules/:scheduleId/imports/preview": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "scheduleId": {
          "type": "string"
        }
      },
      "required": [
        "scheduleId"
      ]
    }
  },
  "POST /v1/schedules/:scheduleId/revisions": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "scheduleId": {
          "type": "string"
        }
      },
      "required": [
        "scheduleId"
      ]
    }
  },
  "POST /v1/subcontractor-assignments/:assignmentId/mobilization-release": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "expectedVersion"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "assignmentId": {
          "type": "string"
        }
      },
      "required": [
        "assignmentId"
      ]
    }
  },
  "POST /v1/subcontractor-assignments/:assignmentId/mobilization-requirements": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "type": "string"
        },
        "category": {
          "type": "string",
          "enum": [
            "license",
            "insurance",
            "safety",
            "quality",
            "commercial",
            "lower_tier",
            "submission"
          ]
        },
        "title": {
          "type": "string"
        },
        "required": {
          "type": "boolean"
        }
      },
      "required": [
        "category",
        "code",
        "required",
        "title"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "assignmentId": {
          "type": "string"
        }
      },
      "required": [
        "assignmentId"
      ]
    }
  },
  "POST /v1/subcontractor-submissions/:submissionId/review": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "expectedVersion": {
          "type": "number"
        },
        "decision": {
          "type": "string",
          "enum": [
            "reject",
            "accept"
          ]
        },
        "meaningOrReason": {
          "type": "string"
        }
      },
      "required": [
        "decision",
        "expectedVersion",
        "meaningOrReason"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "submissionId": {
          "type": "string"
        }
      },
      "required": [
        "submissionId"
      ]
    }
  },
  "POST /v1/subcontractors": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "legalTaxReference": {
          "type": "string"
        },
        "declaredScopes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "geography": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "laborModel": {
          "type": "string"
        },
        "lowerTierDisclosureRequired": {
          "type": "boolean"
        }
      },
      "required": [
        "declaredScopes",
        "geography",
        "laborModel",
        "legalTaxReference",
        "lowerTierDisclosureRequired",
        "organizationId"
      ]
    }
  },
  "POST /v1/subcontractors/:profileId/qualifications": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "profileId": {
          "type": "string"
        }
      },
      "required": [
        "profileId"
      ]
    }
  },
  "POST /v1/turnover/generate": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "packageId": {
          "type": "string"
        },
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "packageId",
        "projectId"
      ]
    }
  },
  "PUT /v1/estimate-lines/:lineId": {
    "body": {},
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "lineId": {
          "type": "string"
        }
      },
      "required": [
        "lineId"
      ]
    }
  },
  "PUT /v1/projects/:projectId/notification-subscription": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "eventTypes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "channel": {
          "type": "string",
          "enum": [
            "in_app",
            "email"
          ]
        },
        "enabled": {
          "type": "boolean"
        }
      },
      "required": [
        "channel",
        "enabled",
        "eventTypes"
      ]
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "type": "string"
        }
      },
      "required": [
        "projectId"
      ]
    }
  }
};
